# This is a basic workflow to help you get started with Actions

name: Build for Milk V Duo S ARM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-for-arm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          path: duo-examples/
          key: duo-s-cache

      - name: Clone toolchain repository if not cached nor found
        run: |
          # Sadece 'duo-examples' dizini yoksa klonla
          [ ! -d "duo-examples" ] && git clone https://github.com/milkv-duo/duo-examples.git
          
          # Dizin zaten varsa, log'a bir mesaj yazdır (iyi bir pratiktir)
          [ -d "duo-examples" ] && echo "duo-examples dizini zaten mevcut, klonlama atlandı."

      - name: Prepare compilation environment and compile the files in repository
        run: |
          cd duo-examples
          echo "--- envsetup.sh çalıştırılıyor (Here Document ile) ---"
          . ./envsetup.sh << EOF
          2
          1
          EOF
          echo "--- envsetup.sh sonrası değişken kontrolü ---"
          echo "CHIP: $CHIP"
          echo "ARCH: $milkv_arch"
          echo "TOOLCHAIN_PREFIX: $TOOLCHAIN_PREFIX"
          echo "CC: $CC"
          echo "CFLAGS: $CFLAGS"
          echo "----------------------------------------"
          cd ${GITHUB_WORKSPACE}/src/
          make
          
      - name: Upload the executable.
        uses: actions/upload-artifact@v5.0.0
        with:
          name: output
          path: src/*.duo
          compression-level: 0
          
